/*
UI JavaScript
Copyright 2013 MCHS Tech Club

* Contains anything related to UI functions, including slideouts,

*/



/* Start Lesson Nav Sidebar */
// Individual menu item slide outs
$(document).ready(function(){
	$(".sidebar .menu-item").hover(function(){
		$(this).animate({marginLeft:"10px"}, 150);
	}, function(){
		$(this).animate({marginLeft:"0px"}, 150);
	});

	$("p > img").each(function(){
		$(this).parent("p").css("margin", "auto");
	});

});
/* End the Sidebar */

/* Settings for modals */
var settings = {
	animation: true,
	highlightTiming: 500,
	highlightColor: "rgba(255,0,0,0.5)",
	// If modal is disabled, reverts back to alert() box
	modal: {
		enabled: true,
		open: false
	}
};

// Opens modal window
// Requires the stats{} object generated by grade() in quizGrader.js 
function $open(data){
	var overlay = $(".overlay");
	var feedback = "";
	if(data.percentCorrect === 100){
		feedback = "Now you understand the problem; let's find the solution together!";
	}
	else if(data.percentCorrect > 80){
		feedback = "You could use a bit more improvement.";
	}
	else{
		feedback = "You may want to review the " + "<a href='../'>lesson</a> ";
	}
	overlay.css( {top: "0px", visibility: "visible", height: $(document).height()+"px"} );
	$(".results-body").html("You earned a "+data.percentCorrect+"%. "+feedback);
	overlay.animate( {opacity: 1} );
	settings.modal.open = true;
}

// Updates modal height upon resize
$(window).resize(function(){
	$(".overlay").css( {height: $(document).height() } );
});

// Closes the modal window
function $close(data){
	$("#top").animate( {opacity:0}, 500, function(){
		$(this).css( {top: "-1000px", visibility: "hidden"} );
	});
}

// Highlights all wrong answers upon grading
function $UIgiveFeedback(data){
	$UIresetPage();
	for(var wrongOnes in data.wrong){
		console.log("Animating..");
		$("#" + data.wrong[wrongOnes]).animate( 
			{backgroundColor: settings.highlightColor}, 
			settings.highlightTiming
		);
	}
}

// Removes the red highlighting of previously graded questions when new answer is chosen
$(document).ready(function (){
	$(".q input").click(function(){
		$(this).parents(".q").animate( {backgroundColor: $("body").css("backgroundColor")} );
	})
});

// Resets the page for each grading 
function $UIresetPage(){
	for(i=1; i<=5; i++){
		$("#"+i).animate( {backgroundColor: $("body").css("backgroundColor")}, 300);
	}
}

